name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  # Sydney region

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://itinteang-cloud-resume-bucket --delete --exclude ".git/*" --exact-timestamps

      # Optional: Invalidate CloudFront cache if using CloudFront
      - name: Invalidate CloudFront cache
        if: ${{ secrets.CLOUDFRONT_DIST_ID != '' }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths "/*"